const API_CONSTANTS = {
  AUTH_TOKEN: `/auth/token`,
  CONTACT_DETAILS: `/contact-details`,
  FOOTER_BLOCKS: `/home/footer-blocks`,
  HOME_MILESTONES: `/home/milestones`,
  HOME_SERVICES: `/home/services`,
  HOME_SERVICES_INTRO: "/home/services-intro",
  HOME_FEATURED_PROPERTIES: `/home/featured-properties`,
  HOME_FEATURED_PROPERTIES_INTRO: `/home/featured-properties-intro`,
  HOME_PROPERTIES: `/home/properties`,
  HOME_PROPERTIES_INTRO: `/home/properties-intro`,
  HOME_PROPERTY_CATEGORIES: `/home/property-categories`,
  HOME_ABOUT_INTRO: `/home/about-intro`,
  HOME_MASTER_SLIDER: `/home/master-slider`,
  SUBSCRIBER_FORM_DETAILS: `/subscriber-form-details`,
  SUBSCRIBER_FORM_DETAILS_API: "/api/subscriber-form-details",
  BANNER: `/banner`,
  META_DATA: `/meta-data`,
  NAVIGATION_MENU: `/navigation-menu`,
  PROPERTY_CATEGORY: `/property-category/{property_category_url_slug}`,
  PROPERTY_CITIES: `/property-cities/{property_category_url_slug}`,
  PROPERTY_STATUSES: `/property-statuses/{property_category_url_slug}`,
  PROPERTIES_BY_CATEGORY: `/properties/{property_category_url_slug}`,
  OTHER_PROPERTY_CATEGORIES: `/other-property-categories/{property_category_url_slug}`,
  PROPERTY_FOOTER_BLOCKS: `/property-category/footer-block`,
};

export default API_CONSTANTS;
