const API_CONSTANTS = {
  AUTH_TOKEN: `/auth/token`,
  CONTACT_DETAILS: `/contact-details`,
  FOOTER_BLOCKS: `/home/footer-blocks`,
  HOME_MILESTONES: `/home/milestones`,
  HOME_SERVICES: `/home/services`,
  HOME_SERVICES_INTRO: "/home/services-intro",
  HOME_FEATURED_PROPERTIES: `/home/featured-properties`,
  HOME_FEATURED_PROPERTIES_INTRO: `/home/featured-properties-intro`,
  HOME_PROPERTIES: `/home/properties`,
  HOME_PROPERTIES_INTRO: `/home/properties-intro`,
  HOME_PROPERTY_CATEGORIES: `/home/property-categories`,
  HOME_ABOUT_INTRO: `/home/about-intro`,
  HOME_MASTER_SLIDER: `/home/master-slider`,
  SUBSCRIBER_FORM_DETAILS: `/subscriber-form-details`,
  SUBSCRIBER_FORM_DETAILS_API: "/api/subscriber-form-details",
  BANNER: `/banner`,
  META_DATA: `/meta-data`,
  NAVIGATION_MENU: `/navigation-menu`,
  PROPERTY_CATEGORY: `/property-category/{property_category_url_slug}`,
  PROPERTY_CITIES: `/property-cities/{property_category_url_slug}`,
  PROPERTY_STATUSES: `/property-statuses/{property_category_url_slug}`,
  PROPERTIES_BY_CATEGORY: `/properties/{property_category_url_slug}`,
  OTHER_PROPERTY_CATEGORIES: `/other-property-categories/{property_category_url_slug}`,
  PROPERTY_FOOTER_BLOCKS: `/property-category/footer-block`,
  PROPERTIES_BY_CATEGORY_API: "/api/properties-by-category",
  PROPERTY_DETAIL: `/property/{property_category_url_slug}/{property_url_slug}`,
  AWARDS: `/awards`,
  AWARDS_API: "/api/awards",
  CLIENTS: `/clients`,
  CLIENTS_API: "/api/clients",
  TESTIMONIALS: `/testimonials`,
  TESTIMONIALS_API: "/api/testimonials",
  PREC_INTRO: `/prec/intro`,
  PREC_INTRO_API: "/api/prec/intro",
  PREC_BENEFITS: `/prec/benefits`,
  PREC_BENEFITS_API: "/api/prec/benefits",
  PREC_FAQS: `/prec/faqs`,
  PREC_FAQS_API: "/api/prec/faqs",
  MEET_THE_CITY_MAGAZINES: `/meet-the-city/magazines`,
  MEET_THE_CITY_MAGAZINES_API: "/api/meet-the-city/magazines",
  ESG_INITIATIVES: `/esg/initiatives`,
  ESG_INITIATIVES_API: "/api/esg/initiatives",
  ESG_COMMUNITIES: `/esg/communities`,
  ESG_COMMUNITIES_API: "/api/esg/communities",
  ESG_POLICIES: `/esg/policies`,
  ESG_POLICIES_API: "/api/esg/policies",
  ESG_MILESTONES_INTRO: `/esg/milestones/intro`,
  ESG_MILESTONES_INTRO_API: "/api/esg/milestones/intro",
  ESG_MILESTONES: `/esg/milestones`,
  ESG_MILESTONES_API: "/api/esg/milestones",
  ESG_AWARDS: `/esg/awards`,
  ESG_AWARDS_API: "/api/esg/awards",
  ESG_REPORTS_INTRO: `/esg/reports/intro`,
  ESG_REPORTS_INTRO_API: "/api/esg/reports/intro",
  ESG_REPORTS: `/esg/reports`,
  ESG_REPORTS_API: "/api/esg/reports",
  ENQUIRY_PROPERTY_FORM_DETAILS: `/enquiry/property-form-details`,
  ENQUIRY_GET_PROPERTY_LIST: `/enquiry/properties`,
};

// Pagination constants
export const PER_PAGE_LIMIT = 5;

export default API_CONSTANTS;
